name: Storybook
on:
  push:
    branches:
      - release # if any push happens on branch `release`, run this workflow
    # paths: [".storybook/**", "src/**"] # trigger the action only when files change in the folders defined here
  
  workflow_dispatch: # enable manual workflow run option

jobs:
  deploy-release:
    # needs: build-and-deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: deploy-release
        uses: wei/git-sync@v3
        with:
          source_repo: "https://joseph-eccles:${{ secrets.PAT_ACTIONS }}@github.com/joseph-eccles/storybook-dev.git"
          source_branch: "main"
          destination_repo: "https://joseph-eccles:${{ secrets.PAT_ACTIONS }}@github.com/joseph-eccles/storybook-release.git"
          destination_branch: "main"

  build-and-deploy-pages:
      needs: deploy-release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install and Build
          run: |
            npm ci
            npm run build-storybook

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            repository: "joseph-eccles/storybook-release"
            branch: gh-pages
            folder: public # output folder from `npm run build-storybook`
