name: Release Branch to Release Repo
on:
  push:
    branches:
      - release # if any push happens on branch `release`, run this workflow
    # paths: [".storybook/**", "src/**"] # trigger the action only when files change in the folders defined here
  
  workflow_dispatch: # enable manual workflow run option

jobs:
  copy-release-branch-to-release-repo:
    # needs: build-and-deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: copy-release-branch-to-release-repo
        uses: wei/git-sync@v3
        with:
          source_repo: "https://joseph-eccles:${{ secrets.PAT_ACTIONS }}@github.com/joseph-eccles/storybook-poc.git"
          source_branch: "release"
          destination_repo: "https://joseph-eccles:${{ secrets.PAT_ACTIONS }}@github.com/joseph-eccles/storybook-release.git"
          destination_branch: "main"
